[Feat]: Export CSV file
BizzNEST/salinas-bizznest-scheduler pull request #66
Opened 2024-10-09 18:24 UTC by jacky-p

## Changes
_List Changes Introduced by this PR_
1. Added Export Button
2. HTML table to CSV file function
3. Added download functionality

## Purpose
Users can download a CSV file of the pairings of interns generated

## Approach
- Added `exportCSV.js` to scripts folder
- 3 functions, one to display the button, one to convert table to CSV, one to download the file

##TODOs
- [ ] Add styling to the button

## Testing Steps
After generating intern pairs scroll to the bottom of the list and click download button, CSV file named `InternPairs.csv` should be downloaded which then can be opened/imported to Google sheets or Excel.

## Learning
- Followed this framework for creating a CSV from an HTML table since we organize our pairing information in a table.
  - [How to export HTML table to CSV using JavaScript ?](https://www.geeksforgeeks.org/how-to-export-html-table-to-csv-using-javascript/)
  - Worked with a lot of text modification to get the right format for the CSV
    - [String `.replace()` to replace new line `\n` with comma](https://www.w3schools.com/jsref/jsref_replace.asp)
    - [String `.split()` to separate text by the commas](https://www.geeksforgeeks.org/convert-comma-separated-string-to-array-using-javascrip)

Closes #62

2024-10-09 19:27 UTC, elimanzo requested changes
Minor Nit and i think we're good to go!

2024-10-09 19:27 UTC, elimanzo commented on src/scripts/exportCSV.js
> +  let rows = table.getElementsByTagName("tr");
not being re-assigned so should be`const` also i think we can remove the intermediate variable
```suggestion
  const rows = document.getElementById("interns-week-table").getElementsByTagName("tr");
```

2024-10-09 19:27 UTC, elimanzo commented on src/scripts/exportCSV.js
> +  let temp_link = document.createElement("a");
objects are mutable so we can have a `const`

2024-10-09 19:27 UTC, elimanzo commented on src/scripts/exportCSV.js
> +  let url = window.URL.createObjectURL(CSVFile);
same as above :)

2024-10-09 23:54 UTC, jacky-p commented on src/scripts/exportCSV.js
> +  let url = window.URL.createObjectURL(CSVFile);
Resolved all the let statements that should be changed to const!

2024-10-10 00:01 UTC, elimanzo approved these changes
LGTM!

2024-10-10 00:05 UTC, merged